//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZenDriveEntities : DbContext
    {
        public ZenDriveEntities()
            : base("name=ZenDriveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Заявки_на_тест_драйв> Заявки_на_тест_драйв { get; set; }
        public virtual DbSet<Кузов> Кузов { get; set; }
        public virtual DbSet<Характеристики> Характеристики { get; set; }
        public virtual DbSet<Электромобили> Электромобили { get; set; }
    }
}
