//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кузов
    {
        public int Код_кузова { get; set; }
        public int Код_электромобиля { get; set; }
        public int длина { get; set; }
        public int ширина { get; set; }
        public int высота { get; set; }
        public int колесная_база { get; set; }
        public string шины { get; set; }
    
        public virtual Электромобили Электромобили { get; set; }
    }
}
