//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Электромобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Электромобили()
        {
            this.Заявки_на_тест_драйв = new HashSet<Заявки_на_тест_драйв>();
            this.Кузов = new HashSet<Кузов>();
            this.Характеристики = new HashSet<Характеристики>();
        }
    
        public int Код_электромобиля { get; set; }
        public string Название { get; set; }
        public string Наличие { get; set; }
        public int Цена { get; set; }
        public string Фото1 { get; set; }
        public string Фото2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки_на_тест_драйв> Заявки_на_тест_драйв { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Кузов> Кузов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Характеристики> Характеристики { get; set; }
    }
}
